Gdk/UnscaledDPI 132710
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName "catppuccin-latte-teal-standard+default"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 32
Gtk/CursorThemeName "catppuccin-latte-teal-cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "breeze"
Gtk/FontName "LXGW WenKai, Medium 12"

